### PR TITLE
fixing exception when setting mq.ssl.use.ibm.cipher.mappings for mq sink connector

### LINKED ISSUE #73: Got exception when setting mq.ssl.use.ibm.cipher.mappings for mq sink connector
When creating connector with **mq.ssl.use.ibm.cipher.mappings**, 
```
{
  ...
  "mq.ssl.use.ibm.cipher.mappings": true,
  ...
}
```
Getting exception:
```
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
    at org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:198)
    at com.ibm.eventstreams.connect.mqsink.MQConnectionHelper.getUseIBMCipherMappings(MQConnectionHelper.java:67)
    at com.ibm.eventstreams.connect.mqsink.JMSWorker.configure(JMSWorker.java:104)
    at com.ibm.eventstreams.connect.mqsink.MQSinkTask.start(MQSinkTask.java:88)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:324)
    at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:176)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:281)
    at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:238)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

In source code, the configuration `CONFIG_NAME_MQ_SSL_USE_IBM_CIPHER_MAPPINGS` is defined as `Type.BOOLEAN` but it is being used as:
```
config.getString(MQSinkConfig.CONFIG_NAME_MQ_SSL_USE_IBM_CIPHER_MAPPINGS)
```

Please check and fix. Thanks.

### PR DESCRIPTION
**Pull request by Adil9645**
Signed-off-by: A S Adil Mohammad <asadilmohammad2020@gmail.com>

# Description

This  pull request fixes the issue of exception when setting mq.ssl.use.ibm.cipher.mappings.In source code, the configuration `CONFIG_NAME_MQ_SSL_USE_IBM_CIPHER_MAPPINGS `is defined as Type.BOOLEAN but it was being used as: `config.getString(MQSinkConfig.CONFIG_NAME_MQ_SSL_USE_IBM_CIPHER_MAPPINGS)`

Fixes #73 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Integration Test

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/integration/java/com/ibm/eventstreams/connect/mqsink/MQSinkTaskIT.java [hunk 1]
```diff
@@ -127,6 +127,44 @@ public void verifyStringMessages() throws JMSException {
...
+
+        // stop the task
+        newConnectTask.stop();
+
+        // verify that the messages were successfully submitted to MQ
+        final List<Message> messagesInMQ = getAllMessagesFromQueue(DEFAULT_SINK_QUEUE_NAME);
+        assertEquals(2, messagesInMQ.size());
+        assertEquals("hello", messagesInMQ.get(0).getBody(String.class));
+        assertEquals("world", messagesInMQ.get(1).getBody(String.class));
+    }
```
Comment (Joel-hanson) [inline src/integration/java/com/ibm/eventstreams/connect/mqsink/MQSinkTaskIT.java]: I think test could be more towards what you are currently doing. that is
1. change the name of the test method
2. Remove unwanted checks
3. Add check to see if it has taken effect (for this it would be something like checking system properties to see the change you did is working)

**Review by Joel-hanson — CHANGES_REQUESTED** [review]

**Review by Joel-hanson — APPROVED** [review]
LGTM
